name: "Genera JSON a partir de los ficheros de objetivos"
on:
  push:
    paths:
      - proyectos/objetivo*.md
      - lib/**
      - t/**

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/jj/raku-github-actions
      env:
        GITHUB_SECRETS: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout this
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache para las distros instaladas
        uses: actions/cache@v2
        id: meta6
        with:
          path: ~/.raku/
          key: ${{ runner.os }}-${{ hashFiles('META6.json') }}
      - name: Instala módulos Raku
        if: steps.meta6.outputs.cache-hit != 'true'
        continue-on-error: true
        run:  raku --version && zef --version && zef install --deps-only .
      - name: Genera JSON
        run: raku -Ilib scripts/iv-objetivos.raku > data/objetivos.json
      - name: Sube JSON actualizado
        run: |
          if [ -n "$(git status -s)" ]; then
              git config --global user.email "jjmerelo@gmail.com"
              git config --global user.name "IVDataBot"
              git commit -am "Actualiza JSON"
              git push
          else
              echo "🟏 No ha habido cambios"
          fi
